CREATE TABLE `JCD_dynamic_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `number` int(11) NOT NULL,
  `status` varchar(45) DEFAULT NULL,
  `bike_stands` varchar(45) DEFAULT NULL,
  `available_bike_stands` varchar(45) DEFAULT NULL,
  `available_bikes` varchar(45) DEFAULT NULL,
  `last_update` timestamp NULL DEFAULT NULL,
  `OYB_timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4889 DEFAULT CHARSET=utf8;
CREATE TABLE `JCD_flask` (
  `number` int(11) NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  `contract_name` varchar(45) DEFAULT NULL,
  `status` varchar(45) DEFAULT NULL,
  `bike_stands` varchar(45) DEFAULT NULL,
  `available_bike_stands` varchar(45) DEFAULT NULL,
  `available_bikes` varchar(45) DEFAULT NULL,
  `last_update` timestamp NULL DEFAULT NULL,
  `address` varchar(45) DEFAULT NULL,
  `OYB_timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lat` float DEFAULT NULL,
  `lng` float DEFAULT NULL,
  `banking` tinyint(4) DEFAULT NULL,
  `bonus` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `OWM_current` (
  `clouds` int(11) DEFAULT NULL,
  `name` varchar(45) DEFAULT NULL,
  `visibility` int(11) DEFAULT NULL,
  `w_d_main` varchar(45) DEFAULT NULL,
  `w_d_id` int(11) DEFAULT NULL,
  `w_d_icon` varchar(45) DEFAULT NULL,
  `w_description` varchar(45) DEFAULT NULL,
  `coord_lat` float DEFAULT NULL,
  `coord_long` float DEFAULT NULL,
  `owm_dt` datetime DEFAULT NULL,
  `id` int(11) DEFAULT '0',
  `humidity` int(11) DEFAULT NULL,
  `pressure` int(11) DEFAULT NULL,
  `temp` int(11) DEFAULT NULL,
  `temp_min` int(11) DEFAULT NULL,
  `temp_max` int(11) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `sys_country` varchar(45) DEFAULT NULL,
  `sys_id` int(11) DEFAULT NULL,
  `sys_message` varchar(45) DEFAULT NULL,
  `sys_sunrise_dt` datetime DEFAULT NULL,
  `sys_sunset_dt` datetime DEFAULT NULL,
  `cod` int(11) DEFAULT NULL,
  `oyb_id` int(11) NOT NULL AUTO_INCREMENT,
  `OYB_timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`oyb_id`)
) ENGINE=InnoDB AUTO_INCREMENT=94 DEFAULT CHARSET=utf8;
